### ISSUE TITLE
Precedence or context

### ISSUE THREAD

**Issue by equwal** [font-lock-cl/font-lock-cl#4]
Currently `#\return` and `(return nil)` both color `return` with the variable face. Fixing this with some source-aware context knowledge would be nice, as it [fundamentally cannot be done with regular expressions alone](https://en.wikipedia.org/wiki/Context-free_grammar).

**Comment by sheepduke** [comment]
True. And the same thing happens if you use any built-in function as a variable name.

For example in 

```lisp
(let ((list '(1 2 3))))
```

`list` will be rendered as a function instead of a trivial variable name.

**Comment by equwal** [comment]
Closing for archival
