### ISSUE TITLE
Not unloadable

### ISSUE THREAD

**Issue by equwal** [font-lock-cl/font-lock-cl#5]
It should be possible to unload this library back to its original state at runtime. Currently it overwrites `lisp-mode`'s default syntax and is not reversible. When `font-lock-cl-mode` is run it should toggle it properly.

**Comment by sheepduke** [comment]
Does it still make sense if this package goes into Emacs core?

**Comment by equwal** [comment]
> Does it still make sense if this package goes into Emacs core?

Well it is clear that some users do not prefer this more complete syntax highlighting, as suggested by the quote in the README. So I think it should be possible to unload the additional highlighting at runtime.

**Comment by sheepduke** [comment]
On 2020-03-21 11:50, Spenser Truex <notifications@github.com> wrote:
>> Does it still make sense if this package goes into Emacs core?
>
> Well it is clear that some users do not prefer this more complete syntax highlighting, as suggested by the quote in the README. So I think it should be possible to unload the additional highlighting at runtime.
>
Maybe this may default to be on, and we provide a variable like
`use-legacy-highlighting` or something to turn it off.

**Comment by equwal** [comment]
Closing for archival
